# docker-compose.yml
version: '3.6'
services:
  jenkins:
    image: jenkins/jenkins:latest
    privileged: true
    user: root
    ports:
      - 8083:8080
    container_name: jenkins-dataform
    volumes:
      - ~/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock