config {
  type: "view",
  assertions: {
    rowConditions: [
      'country = "Brazil"'
    ],
    nonNull: ["transactionRevenue"]
  },
  description: "Description Transaction",
  columns: {
    country: "Country column",
    transactions: "Transaction column"
  }
}

select
  *
from 
   ${ref("all_sessions")}
where transactionRevenue is not null
and country = "Brazil"
and date >= ${constants.MIN_DATA}
